// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2vQ12oP6ZjQw09wJu49TE7H0ZsTABzOw',
    appId: '1:691872778978:web:26b2d6d30a6c166c262cbb',
    messagingSenderId: '691872778978',
    projectId: 'kol-shaket',
    authDomain: 'kol-shaket.firebaseapp.com',
    storageBucket: 'kol-shaket.firebasestorage.app',
    measurementId: 'G-BNTZ03FFM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvEIKgnhXBd-XJxavAJUbN6nw7ms-34P0',
    appId: '1:691872778978:android:785db8ccf1d8a639262cbb',
    messagingSenderId: '691872778978',
    projectId: 'kol-shaket',
    storageBucket: 'kol-shaket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiiHrMADUByqoeNS_hJQEg_nO6Vl5ScT0',
    appId: '1:691872778978:ios:46a84c65eab9775b262cbb',
    messagingSenderId: '691872778978',
    projectId: 'kol-shaket',
    storageBucket: 'kol-shaket.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiiHrMADUByqoeNS_hJQEg_nO6Vl5ScT0',
    appId: '1:691872778978:ios:46a84c65eab9775b262cbb',
    messagingSenderId: '691872778978',
    projectId: 'kol-shaket',
    storageBucket: 'kol-shaket.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2vQ12oP6ZjQw09wJu49TE7H0ZsTABzOw',
    appId: '1:691872778978:web:a0cbc1fab083f922262cbb',
    messagingSenderId: '691872778978',
    projectId: 'kol-shaket',
    authDomain: 'kol-shaket.firebaseapp.com',
    storageBucket: 'kol-shaket.firebasestorage.app',
    measurementId: 'G-Q59NHGVL8W',
  );
}
